public enum ReturnMessage {
    GOOD_TO_USE,
    EQUIPPED,
    ALREADY_EQUIPPED,
    NOT_USABLE,
    NOT_FOUND,
    MELEE_ATTACK,
    RANGED_ATTACK,
    NOT_EQUIPPED,
    AMMO,
    NO_AMMO,
    NOT_RIGHT_WEAPON,
    ENEMY_DEAD,
    ENEMY_ALIVE,
    GAME_OVER,
    NO_ENEMY_FOUND
}
