public enum ReturnMessage {
    GOOD_TO_USE,
    EQUIPPED,
    ALREADY_EQUIPPED,
    NOT_USABLE,
    NOT_FOUND,
    MELEE_ATTACK,
    RANGED_ATTACK,
    NOT_EQUIPPED,
    NO_AMMO,
    NOT_RIGHT_WEAPON
}
